### ISSUE TITLE
Why Full-stack JavaScript?

### ISSUE THREAD

**Issue by nelsonic** [foundersandcoders/oursite#1]
We use JavaScript throughout our work because it means our people only have to know *one* language (*really well*). This means the code we craft is easier to maintain and support.

Thankfully, given the recent surge in popularity of "full-stack javascript" (using node.js), you are in good company: http://stackshare.io/node-js/in-stacks

**Comment by sofer** [comment]
@nelsonic have added a note about this to https://github.com/foundersandcoders/oursite/blob/master/_content/training.md

**Comment by nelsonic** [comment]
Reads well. :+1:

**Comment by izaakrogan** [comment]
@sofer leaving this for you

**Comment by sofer** [comment]
Have added this copy back into the site in the academy suggesting under the why-javascript branch. Ready to pull.

**Comment by sofer** [comment]
I think we can close this one.
