### ISSUE TITLE
Sort out nesting in portfolio

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/oursite#103]
@sofer

**Comment by iteles** [comment]
@izaakrogan If you actually assign the issue to @sofer then he can run a simple query in the search bar to pick up all the outstanding stuff he's supposed to be looking at.
This is how I manage my issues and it makes life a lot easier :blush: (I use `assignee:iteles is:open` as my search string).

**Comment by izaakrogan** [comment]
Thanks again @iteles

**Comment by iteles** [comment]
@izaakrogan :+1: :blush:

**Comment by sofer** [comment]
Not sure that this is still relevant.
