### ISSUE TITLE
Missing title in <head> element

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/oursite#105]
The result is the tab in [insert browser of choice] ends up looking something like:
![fac-title-missing-chrome-tab](https://cloud.githubusercontent.com/assets/4185328/8138997/f52fd11a-1147-11e5-8b60-ffd48dcfbcac.png)

```html
<title>Founders &amp; Coders - A co-operative of coders in London</title>
```

**Comment by izaakrogan** [comment]
@iteles Thanks!
