### ISSUE TITLE
Contact email - .org not .com

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/oursite#109]
Any way we can get our email address to be .com? It looks odd having .org email address but .com site

**Comment by izaakrogan** [comment]
@sofer

**Comment by sofer** [comment]
@izaakrogan @rub1e, in progress.

**Comment by sofer** [comment]
contact@foundersandcoders.com is now set up. It can be changed on the site.

**Comment by iteles** [comment]
@sofer What about on all our individual emails? Do we now all own both a .com and a .org?

**Comment by sofer** [comment]
@iteles you have both. I am now using .com by default if people ask for it, but existing .org emails should still work.
