### ISSUE TITLE
What do you think of the mock-ups?

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/oursite#11]
https://drive.google.com/folderview?id=0B4bVziUnoiEbfjh0ang0NFA4cGFKSUpGcklGVWRKbEtfdUxpQVJuU0VHWkpDQ0hQOUF0YUE&usp=sharing

**Comment by iteles** [comment]
Looking good so far :+1: 
I'm a fan of having the contact form in the footer.
I think it might be worth displaying some actual information about the projects on the Work page (but agree with keeping the portfolio on the homepage minimal with just an overlay title on the image or a one sentence underneath)

**Comment by izaakrogan** [comment]
@iteles 
I was thinking overlay for each image, with a modal dialogue for additional information. Not too dissimilar to https://8thlight.com/portfolio/

**Comment by nelsonic** [comment]
Overlay for each image will be good.
Modals are evil. when usability studies are conducted modals *often* frustrate and confuse people.
***side note***: does 8thLight only have 10 things in their portfolio...? https://8thlight.com/portfolio/
