### ISSUE TITLE
Copy editing

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#12]
@izaakrogan as soon as you want us to start providing copy, let us know.

**Comment by izaakrogan** [comment]
The sooner the better!

**Comment by sofer** [comment]
@izaakrogan would you mind creating some placeholder md files and we can start adding copy to them.

**Comment by sofer** [comment]
@iteles @nelsonic @harrygfox @GBGuinan we are currently in the process of adding copy to the site in the _content directory. First drafts of all the copy should be ready in the next hour or two. Reviews and contributions are welcome any time. I think we are hoping to go live with the site later this week, although there is still a fair bit of work to do on it.

**Comment by sofer** [comment]
@rub1e feedback and edits to existing drafts would be welcome.

**Comment by sofer** [comment]
I should also say that, on the basis of recent discussions, I am thinking of removing references to the cost of the MVP/prototype from the website.

**Comment by sofer** [comment]
@izaakrogan and @rub1e, I have added some new copy for training for commissioning staff from local authorities: https://github.com/foundersandcoders/oursite/blob/services-copy/_content/product-management.md

I don't even know if this is a product that anyone will want to buy, but I am going to attempt to start selling it to local authorities (and others) next week.

**Comment by sofer** [comment]
Closing this now.
