### ISSUE TITLE
Simple SEO fixes

### ISSUE THREAD

**Issue by joshpitzalis** [foundersandcoders/oursite#131]
These are suggestions for the Training page only. I can work on a separate campaign for each page of the site. I thought it made sense to focus on this page first since training courses can bring in the most money in the short term. 

I have used google adwords keyword planner to search for likely keywords I would enter if I were looking for a weekend javascript course in london.

I got the following results for people searching from london https://docs.google.com/spreadsheets/d/1ElyTs_q_JEDm4hky-fpsEk7KTp1cYx-IXCpyIF4x4v0/edit?usp=sharing

I suggest we focus on "javascript course london". 

The keywords above it get searched for more but they are vague. It is not clear whether somone searching for 'learn javascript' could be looking for a weekend course, an online course or blog post. More specific keywords, like 'node.js training' only get searched for 10 times a month in london (the results are not exact values but they are indicative relative search proportion).

"javascript course london" has almost twice as many searches as "javascript courses london" (plural) and since it is awkward grammar it is less likely to be targeted by competitors. If we search for 'javascript course london', we have to beat coderwave.com to get on the first page. 

I put coderwave into spyfu and it doesn't look like they are fighting for their position. http://www.spyfu.com/overview/domain?query=http%3A%2F%2Fcoderwave.com%2F

If we get some press, toppling them off the first page is a realistic goal.

##To Do:

+ [x] Put the following in the head of the http://www.foundersandcoders.com/training/ page
```js
<meta name="google-site-verification" content="mOpWptCT92oi7c5sI1qLgywVvQyN8eAalYCjl3qNurw" />
<meta name="google-site-verification" content="mOpWptCT92oi7c5sI1qLgywVvQyN8eAalYCjl3qNurw" />
```

+ [x] Add the following script to the page http://www.foundersandcoders.com/training/ page

```js
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61056964-2', 'auto');
  ga('send', 'pageview');

</script>
```

+ [x] In the footer (ideally for all pages but at least the training page) replace the contact div with the following. I have added schema tags so that google understand what the details correspond to:

```js
<div class="contact">
	<div class="container">
		<div itemscope itemtype="http://schema.org/LocalBusiness" class="grid-6 info">
			<!--  <h2> </h2>  -->
			<p itemprop="telephone">+44 20 3583 2442</p>
			<a href="mailto:contact@foundersandcoders.org"><p itemprop="email">contact@foundersandcoders.org</p></a>
			<p itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
<span itemprop="streetAddress">14 Palmers Road</span>, 
<span itemprop="addressLocality">London</span> 
<span itemprop="postalCode">E2 OSY</span></p>
			<p>
<span itemprop="name">FOUNDERS & CODERS</span> C.I.C. <br/> Company No. 09408874</p>
			<div>
```

+ [x] Add a static dive to the top of the http://www.foundersandcoders.com/training/ page, below the picture but above the course explanations. The following must a H1 tag:

"Find the Best Weekend Javascript Course London Has to Offer"

The wording is totally negotiable just as long as the h1 tag contains target phrase. 
For the H2 we could use the following.

"Founders and Coders offer the following upcoming weekend classes and training workshops for software developers."

The wording of  H2 is also completely negotiable. The important thing is that it is static and stays on the page, as opposed to the course description text, which will be renewed every month.

+ [x] In the head change the header to "Javascript Course London". Strangely this is one of the most important things we do. I don't understand why but apparently header text is a big deal.

+ [x]  Add a meta description tag to the head. Wording negotiable just has to be around 160 characters. Google only uses this if they like our page.

```js
<meta name="description" content="Javascript Courses in London | Founders and Coders offers the following upcoming weekend classes and training workshops for software developers.">
```

I can do all the rest on my own after those tags at the top have been verified. I will send anyone who is interested access to the analytics and webmaster tools. Once we have a week of analytics for a baseline, I will start AB testing the content to get better conversions. 

I also think we should have dedicated pages for each of our courses. I will put together a proposal for what each page should say once the course is finished and I have some time. 

If someone could have a look at validating the HTML and dealing with the google page speed issues it would be super helpful.

**Comment by iteles** [comment]
Had a quick glance through this @joshpitzalis, nice work! 

2 notes:
+ We definitely already have an analytics account and I see an [async call to google-analytics](https://developers.google.com/analytics/devguides/collection/gajs/) already (I don't have access but I'm sure @sofer or @izaakrogan can check if we're already pulling in metrics for the training page and give you access for further analysis)
+ Would definitely be worth abstracting out the more general 'SEO learnings' here so there's a blueprint that someone can pick up and apply to every page

**Comment by joshpitzalis** [comment]
Thought of a better H1 tag and edited the issue above. Can definitely put together a blueprint, after next week.

**Comment by izaakrogan** [comment]
@joshpitzalis can you check the edits and let me know if you're happy with them. I did some Googling and it looks like commas don't affect SEO.

**Comment by joshpitzalis** [comment]
Looks super, thank you. Google master is also verified now so we're doing much better already. I will track the ranking for different keywords and post updates here at least once a week.

**Comment by iteles** [comment]
@joshpitzalis Very much looking forward to the blueprint post :blush: :+1:

**Comment by joshpitzalis** [comment]
@iteles am I putting together my limited understanding of technical seo best practices or is there something specific you want me to think about?

**Comment by iteles** [comment]
@joshpitzalis Whatever you know of/have researched is a great starting point! We can then develop it into a quick reference F&C guide to SEO :wink:

**Comment by iteles** [comment]
Did this ever get done and PRed?

**Comment by joshpitzalis** [comment]
@iteles Still on my to do list. Will block out some time to work on this post on thursday. What does PRed mean?

**Comment by iteles** [comment]
PR as short for pull request :blush: You're absolutely right @joshpitzalis, thanks for reminding me not to use 'jargon'!
I was actually referring to the main subject of the issue, not the post itself (though that would be lovely of you of course!). From the comments it looks like the changes were made so the issue can be closed if you're happy Josh :+1:  (maybe open another one for the article if you feel you have time :blush:)
