### ISSUE TITLE
 Hovering over items in nav bar doesn't always bold text

### ISSUE THREAD

**Issue by msmichellegar** [foundersandcoders/oursite#137]
When you hover over items in the nav-bar, the text only bolds when you directly hover over a word.

I feel like since the dropdown menu/second nav-bar appears even when you just hover in the general vicinity of a menu item, logically it makes sense to also bold the text -- or else it feels like you haven't "truly" hovered over a menu item.

**Comment by msmichellegar** [comment]
(It also can be confusing, since you're not sure which menu item you are currently hovering over).

**Comment by izaakrogan** [comment]
Agreed. Sorted!

**Comment by msmichellegar** [comment]
Awesome.
