### ISSUE TITLE
Dead Link - training/_request.md

### ISSUE THREAD

**Issue by harrygfox** [foundersandcoders/oursite#149]
## Dead link

Clicking the link at [/training](http://www.foundersandcoders.com/training/#request) has no effect for me. 

### Console Error Reads:
`Uncaught TypeError: Cannot read property 'offsetTop' of null`

### This is where the link can be found:
https://github.com/foundersandcoders/oursite/blob/master/_harp/training/_request.md

* I am using Chrome 44 on a MacBook Pro Late 2013 *

**Comment by sofer** [comment]
The training is no longer linked to. Closing.
