### ISSUE TITLE
Could we be using the 'hexagons' space on the homepage for more sought after information?

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/oursite#161]
Although the hexagon series on the homepage is _pretty_, I'm not sure they actually convey any information. I thought there might be some feedback on mouse-over that told me where each tile would take me but it looks like a block that will take me to the academy section (though I only know that because I was looking for it, I don't think this is how the majority of people navigate websites).

It might be worth finding out from our students and potential clients what the most important information is to them and replacing this block with that (still in keeping with the minimalist design).

<img width="809" alt="fac-hexagons" src="https://cloud.githubusercontent.com/assets/4185328/9831009/88544218-593d-11e5-929c-555ce2f3e3a4.png">

**Comment by izaakrogan** [comment]
very much a temp fix! :smile:
