### ISSUE TITLE
Recurrent Typo in Niki & Simon's Testimonials

### ISSUE THREAD

**Issue by nelsonic** [foundersandcoders/oursite#166]
![image](https://cloud.githubusercontent.com/assets/194400/9974428/01500bdc-5e86-11e5-8eeb-0ba09bd926ab.jpg)
![image](https://cloud.githubusercontent.com/assets/194400/9974429/0153060c-5e86-11e5-8d24-1706510722a3.jpg)

**Comment by izaakrogan** [comment]
Well spotted. Thanks! :smile:
