### ISSUE TITLE
contact form address

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/oursite#168]
Is there any way we can send contact form queries to a different address? At the moment, they go to contact@, but that's also the address we've used for ebay, twitter etc. It would be much easier to keep track of incoming queries from the form if they didn't get buried under all the marketing emails

@sofer

**Comment by iteles** [comment]
Good shout @rub1e. I suggest `hello@`

**Comment by sofer** [comment]
@rub1e I have set up hello@foundersandcoders.com, but we need @besarthoxhaj  to change http://founderscoders.herokuapp.com/email.

**Comment by iteles** [comment]
@besarthoxhaj @sofer 
Do we have a central location with our passwords? i.e. Do we have any passwords that we would lose if a single person gets hit by a bus?

**Comment by rub1e** [comment]
We should also make sure that Dan, Ines, and Nelson never travel on the same bus together

@iteles kinda - I'm more like the EA who triages the boss' incoming mail to weed out the people asking stupid questions like "Have I missed the deadline?" (read the goddamn website) or reasonable questions like "Can I apply if I'm an international student" (yes, but no Welsh or Aussies during the rugby world cup. Or Kiwis. Or French. South Africans are fine after their humiliation the other day.).

**Comment by iteles** [comment]
@rub1e 😄 We need to get your sarcasm emoji!

**Comment by besarthoxhaj** [comment]
Hi guys! I just transferred the ownership of the heroku instance to Dan and the repo to `foundersandcoders`.

**Comment by besarthoxhaj** [comment]
@rub1e @iteles @sofer the repo is: https://github.com/foundersandcoders/mail-fac

**Comment by sofer** [comment]
@rub1e  hello@foundersandcoders.com. Done.
