### ISSUE TITLE
Add 'tick this box if you would like to apply for financial support' item to application form

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/oursite#169]

**Comment by rub1e** [comment]
are we able to offer financial support? If so, should we have a discussion about who would be eligible?

**Comment by izaakrogan** [comment]
We don't yet have have the capacity for financial support. This is more about demonstrating the need to potential partners, right @NataliaLKB ?

Natalia how do you think we should word this?

**Comment by NataliaLKB** [comment]
Yes this is simply collecting data at this point and nothing else. Once we know there is interest we can discuss the next stage.

**Comment by NataliaLKB** [comment]
I believe @rjmk was assigned to this task in the meeting? At this stage I think keeping it short and sweet is the key.

If there is interest then coming up with a form for those students to fill out seems to be the logical next step. I don't think there is any sense wasting time on that now until we know there is interest though.

**Comment by izaakrogan** [comment]
@NataliaLKB do you think the Guardian might be up for helping us out with interest free loans for students? 4K would probably be enough for a single person to get by for 16 weeks and I imagine it could be paid back within 8-16 weeks. 4K could probably improve the accessibility of our course for 2 students a year with an opportunity cost of about £200 (assuming a completely arbitrary return of 5%). Is this something you could suggest at your next focus group? I've also added something to the [partners page](http://www.foundersandcoders.com/partners/). Maybe we could tidy that up a bit and get some help with publicity.

This is probably more a point for after we've demonstrated interest but it can't hurt to jot down some ideas!

**Comment by NataliaLKB** [comment]
Certainly! Brainstorming ideas is perfect. Once we get some interest from potential students I will discuss further with the Diversity group.

I like what you put on the partners page. :star:

**Comment by iteles** [comment]
We definitely [agreed in the business meeting](https://hackpad.com/Business-Meeting-Z4wmOeeBDqv#:h=Minutes) that @rjmk would own this :blush:

**Comment by rjmk** [comment]
I will make a PR this weekend. Are we happy for it to be in the application form? It's possible some people in need of financial support a dissuaded before applying; on the other hand, they may well still look at the form.

**Comment by sofer** [comment]
@rjmk added as editor on Part 2 of application form https://docs.google.com/forms/d/1qqD_b0XcKE12mtMnj5Hbw_5dYJm-AcwlaezSidhw-NM/edit

**Comment by rjmk** [comment]
Checkbox added -- right at end of Part 2 as seemed to fit most there. Again, not sure how many people will get that far

**Comment by sofer** [comment]
Thank you @rjmk. I added a parenthetical note that we do not yet actually offer any support. I do not want to give the impression that we actually have a fund in place already. It's here: http://www.foundersandcoders.com/academy/apply2.html. 

@izaakrogan ready to close?

**Comment by iteles** [comment]
@sofer I thought the whole point was that this is a trial to see if we get any interest - i.e. people bothering to click through. Encouraging people who know they can't afford to do it to apply.
We noted that if for some reason the Guardian decided sponsorship wasn't on the cards then we would tell people that they didn't get the sponsorship without  needing to go into detail. If we add a note then it seems to me that this makes the whole thing very hypothetical again rather than a real measure of whether this is viable or not...

**Comment by NataliaLKB** [comment]
@iteles is completely right. This is purely collecting data to see if there is interest and nothing more.

**Comment by iteles** [comment]
@izaakrogan @NataliaLKB But wait, what about the issue of the note? Do we have consensus on whether it makes the whole thing a little less realistic again?

**Comment by izaakrogan** [comment]
@iteles I thought we might revisit this only after we've received feedback but I've reopened for further discussion.

**Comment by NataliaLKB** [comment]
@izaakrogan you are correct that we are revisiting this once we have received feedback. However this initial step can't be done until we decide on whether to remove or keep the note that @sofer added in.

I think it should be removed.

**Comment by sofer** [comment]
Note removed.

**Comment by iteles** [comment]
@izaakrogan All yours :ok_hand:

**Comment by NataliaLKB** [comment]
:+1: thanks!
