### ISSUE TITLE
Employers Area Spelling Mistake

### ISSUE THREAD

**Issue by thegsi** [foundersandcoders/oursite#175]
https://github.com/foundersandcoders/oursite/blob/master/_harp/employers/index.ejs#L10

'The 5% of applicants that get excepted are passionate learners. '  Should be spelled Accepted not Excepted. Also that 'are accepted' reads better. I also feel that this paragraph/section would benefit from some rewriting, I can help!

Our People
Our students are exceptionally motivated. Applicants need to put in around 200h of work before we consider them in the selection process. The 5% of applicants that get excepted are passionate learners. We value hard work, talent and diversity - with around 40% of our intake being female and many from groups underrepresented in the tech industry. Our selection process is simple: We take people we would want to work with at our own startups.

**Comment by iteles** [comment]
@thegsi A PR is very welcome 😊

**Comment by sofer** [comment]
Thank you @thegsi.

@iteles PR awaiting merger.

**Comment by sofer** [comment]
@thegsi typo fixed, but re-write very welcome.
