### ISSUE TITLE
Agency section rewrite required

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#179]
This section no longer reflects how we engage with clients. 

http://www.foundersandcoders.com/agency/

It also does not provide enough prominence to the graduate prototyping service.

http://www.foundersandcoders.com/agency/services/prototyping

**Comment by rub1e** [comment]
I think we might be ready for a complete update of the whole site - esp with dwyl - but generally I think it could all be better organised

I'm not sure just tweaking will be enough

**Comment by sofer** [comment]
@msmichellegar see https://github.com/foundersandcoders/business/issues/61 for a list of the lovely organisations we are now working with. It would be great to have some way of being able to add references to them (i.e. their logos) on the site along with dwyl. 

I would like to retire the *agency* section and replace it with a *partners* section instead. 

(@rub1e was right that this is *just tweaking*, but the *complete update* he envisaged last year may still be some way off and these minor changes will support the conversations I am now having no end.)
