### ISSUE TITLE
Visible Markdown syntax on website

### ISSUE THREAD

**Issue by harrygfox** [foundersandcoders/oursite#180]
Unlike the way github renders markdown (here https://github.com/foundersandcoders/oursite/blob/master/_harp/agency/portfolio/chichester-harbour.md) with single # signs being converted to h1 etc, the website actually displays the # (here http://www.foundersandcoders.com/agency/portfolio/chichester-harbour).

Expected view:
# Title

Actual view:

#title

**Comment by iteles** [comment]
Might be because there's no space between the hash `#` and the `title`. Causes a lot of mis-rendering.

**Comment by harrygfox** [comment]
@iteles I suspect so :)

**Comment by sofer** [comment]
@iteles @harrygfox that is precisely the problem. Re-publishing shortly.

**Comment by iteles** [comment]
@sofer This is actually present in quite a few places. e.g. http://www.foundersandcoders.com/agency/portfolio/stockport

**Comment by rub1e** [comment]
have done a few PRs for this - not sure if I've got them all... also, pretty sure I may have pushed directly to master on one of them...

**Comment by iteles** [comment]
Think you got them all @rub1e, thanks!
