### ISSUE TITLE
Wrong logo???

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/oursite#181]
The logo on the ```/academy``` [page](http://www.foundersandcoders.com/academy/) seems to be the wrong one. At any rate, it's not the same as our stickers - there's no soil under the plant.

Site:
![SITE](https://cloud.githubusercontent.com/assets/11595920/11086938/d8de9186-884d-11e5-9247-3fa788b96868.png)

[Sticker:](https://drive.google.com/file/d/0B9NH5BWy2_lXaWNvc2g4VTFXR24xOXlUWUU4Snc1Qnh3c2Y0/view?usp=sharing)

Is this deliberate or an oversight?

**Comment by sofer** [comment]
@rub1e well-spotted. This is the one we want.

![lightbulb-no-opacity](https://cloud.githubusercontent.com/assets/37059/11088744/7b25ed3c-885c-11e5-8489-b076e3483c33.png)

**Comment by rub1e** [comment]
I was just trying to update with the right logo and noticed there's a random bit of turquoise in the bottom right of this image - do we have a clean one? Or does someone have access to photoshop or whatever to crop it?

**Comment by iteles** [comment]
Use pixlr https://pixlr.com/

**Comment by iteles** [comment]
Closing as this page no longer exists.
