### ISSUE TITLE
Homepage hero image could be less chaotic?

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/oursite#191]
Currently the homepage [hero image](https://en.wikipedia.org/wiki/Hero_image) is this photo:
<img width="1346" alt="screen shot 2015-12-07 at 10 19 55" src="https://cloud.githubusercontent.com/assets/4185328/11624493/363b3fb8-9ccc-11e5-902d-fa285684d1c6.png">

I :heart: this photo as a portrait of 'us' but I don't think it's right for the homepage. My first impression is that this is a 'disorganised' and 'somewhat chaotic' group of people and I don't think that's what we want to put across.

I would suggest a more 'posed' homepage image with this one to juxtapose it (if we like) when we come to a different section of the site.

What do people this?

**Comment by NataliaLKB** [comment]
I do love this picture, however I am inclined to agree with you. Do you have a better picture in mind?

**Comment by iteles** [comment]
@NataliaLKB I was thinking that the actual photo we were intending to take (the organised one with everyone looking at the camera) would be ace for now and then we can periodically refresh it.

**Comment by msmichellegar** [comment]
Agreed! +1

**Comment by iteles** [comment]
😊 @msmichellegar 👋🏻

**Comment by sofer** [comment]
Let's update it. Could somebody organise a group shot, please.

**Comment by iteles** [comment]
Failing that we have a very good group shot from that same photo shoot which is the non-chaos version (as a stop-gap).

**Comment by sohilpandya** [comment]
Can we close this issue as the site has been updated with a less chaotic photo? (I think. 😟)

**Comment by iteles** [comment]
Yes! :+1: only took a year :wink:
