### ISSUE TITLE
Clarification for overseas applicants

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#195]
We need to make it clearer to overseas applicants that we expect people to stay in London after the course ends and look for work Perhaps, we should remove the *"Would you stay in London?"* options and just ask people that they intend to stay in London and look for work.

**Comment by rub1e** [comment]
We could bake it into the start of the whole process - we could have a "before you apply read this" link with the FAC "contract" we developed?

**Comment by sofer** [comment]
@rub1e Agreed. I have just made a pull request for the FAQ and will update the copy elsewhere to reflect your suggestion.

**Comment by sofer** [comment]
@rub1e Copy tweaks published. Closing now.
