### ISSUE TITLE
Friends of Chichester Harbour case study

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#20]
@besarthoxhaj @FilWisher could you cast your eyes over https://github.com/foundersandcoders/oursite/blob/content/_content/fch.md and round it out with more material. It's still quite a way off @NataliaLKB's magnificent case study here: http://foundersandcoders.org/dossier/studies/camdenmaps, but I am hoping we can get it ready for publication in the next few days.

Thank you :-)

**Comment by sofer** [comment]
@besarthoxhaj @FilWisher I think your approach has changed a bit in the last week. Could you add a couple of paragraphs and a screenshots before next week, so that we can add it to the new site.

**Comment by besarthoxhaj** [comment]
@sofer so much to write about it! I will do my best to have something ready as soon as possible!

**Comment by sofer** [comment]
@besarthoxhaj we still need a screenshot.

**Comment by izaakrogan** [comment]
closing this in favour of more specific issue
