### ISSUE TITLE
New website brief

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#200]
We did not quite get a resolution to the question posed here https://github.com/foundersandcoders/oursite/issues/2, but perhaps we have enough to give some assistance to framing a new website brief.

If you look at our current website, it falls short in a few important use cases, as @rub1e and I can tell from the enquiries we get. In particular, candidates do not always find everything they need to about the course and potential clients (either for our MVPs or for dwyl) don't find out enough about working with us. 

For now, I would like our website to focus on two groups of people: potential candidates and potential clients for projects.

For candidates, I think we want:
+ A clear call to action
+ the material we already have at http://www.foundersandcoders.com/academy/
+ course curriculum
+ graduate stories

For clients, I  think we want:
+ A clear call to action
+ the material we already have at http://www.foundersandcoders.com/agency/services/prototyping
+ a clear message about the difference between our graduate prototyping service and a dwyl project
+ client stories

There are (I think) two other things missing from our current site: 
+ our partners, see https://github.com/foundersandcoders/oursite/issues/172
+ space for announcements, e.g. workshops

On our current site, I don't think the Employers or Partners sections serve any great useful purpose and, so far as I can see, can go. The About section currently has the super-important mugshots, but these needs updating and they needs quick blurbs, like on the front page (e.g. Natalia Baltazar, Developer at  The Guardian. *"Hands down the best experience of my life."*). Once that is done, perhaps these could go on our front page below the calls to action.

And the calls to action on the front page could be much clearer than they currently are: 
+ "Look! We run a great course. Applications for May/September/January are now open. Apply here!"
+ "Look! We can help you with your MVP. Book an appointment here!"

What have I missed?

I am hoping that somebody will be willing to take on this brief in January. In the mean time, let's start gathering content.

**Comment by iteles** [comment]
We definitely need to clarify where the commercial work sits and how this is split between us as part of what goes on the website :+1: Suggest we talk through this in the first week of January face-to-face as per https://github.com/foundersandcoders/marketing/issues/2#issuecomment-167014425

**Comment by sofer** [comment]
A Suggestion. For the new site, we keep in mind just two main groups:

+ Women and non-graduates thinking of applying for the course;
+ People that have heard about our prototyping service and want to know more.

I don't think we need "better" applicants, but we would benefit from more diversity and, in particular, more women and more people without degrees. If we can increase good applications from those two groups I will be very happy.

The prototyping service. For now, let's just make sure that the website does a really good job of helping people  understand how the prototyping service works and why it is going to be such a good choice for them.
