### ISSUE TITLE
Grid layouts

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#205]
There is another issue open on the topic of the [New website brief](https://github.com/foundersandcoders/oursite/issues/200), but I want to open this issue to explore grid layouts for four kinds of content that are important to the site:
- testimonials from graduates
- testimonials from employers and partners
- testimonials from clients 
- links to editorial content and blog entries
- links to learning resources/READMEs

I think it is worth putting a bit of effort into thinking about how to present this stuff.

**Comment by sofer** [comment]
[Our current testimonials page](http://www.foundersandcoders.com/testimonials/). We can do better.

**Comment by iteles** [comment]
I'd question the framing of the testimonials from clients if the plan is that client work will not be done through F&C at all... We probably need to rethink the context there!

**Comment by sofer** [comment]
@iteles we still want to showcase the work of our members and particularly the graduate projects. It's not so much *here is what we (FAC) have done*, as *here is what our members are capable of*. I am also hoping that we can get some nice feedback in the Spring from our participation in various hackathons-- which may well be a direction that we increasingly go in for future cohorts.

**Comment by sofer** [comment]
Some nice layouts from codrops:
+ [Grid Loading Effects](https://github.com/codrops/GridLoadingEffects)
+ Some nice [dialog effects](https://github.com/codrops/DialogEffects)
+ and [page transitions](https://github.com/codrops/PageTransitions)
+ a magazine-style [animated grid layout](https://github.com/codrops/AnimatedGridLayout)

Some nice libraries:
+ [Isotope](http://isotope.metafizzy.co/)
+ [Animate.css](https://daneden.github.io/animate.css/)
+ [Hover.css](http://ianlunn.github.io/Hover/)
+ [Sequence.js](http://www.sequencejs.com/)

**Comment by iteles** [comment]
@sofer Totally agree that that's the correct framework. Maybe it's more a showcase of our graduates' work with testimonials from _their_ clients.

**Comment by sofer** [comment]
:+1: 

The way I was thinking of a lot of the content was as signposts to stuff hosted elsewhere. The best examples of this are links to learning resources, most of which are spread over various accounts on GitHub, and articles by alumni, several of which have been posted to medium. Regarding clients, I would be quite keen for us to signpost launched dwyl projects, but I would not expect to host the actual case studies on the FAC site--just link to the case studies on dwyl.io.
