### ISSUE TITLE
Change subject of emails sent to us from contact form

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/oursite#206]
We're currently in the unendingly frustrating situation where all emails we get form the contact for come from the same sender _and_ have the same email address. This means gmail (which most of us use to manage emails) chains them all together which makes them completely unmanageable.

Can we PLEASE add a differentiator into the subject line of the email such as the person's email address?

**Comment by rub1e** [comment]
@iteles do you mean the form at the bottom of the page that goes to hello@ ? For me they all have the sender as the email address entered on the form - so I have multiple threads with the same subject but categorised as different conversations by gmail as they have different senders

Is this not what's happening for you?

**Comment by rub1e** [comment]
Oh hang on - is this because it's me that's forwarding them to you?!

**Comment by iteles** [comment]
Yep :blush: But that will happen to everyone that gets emails forwarded to them.

**Comment by rub1e** [comment]
yeah sorry I didn't mean to diminish your frustration - it just hadn't dawned on me that was the reason!

@rug1 will you have time to take a look at this and see if you can make the subject line be of the form ```"FAC contact " + sender's email```?

Do we know who did the code for that in the first place? Perhaps they can offer guidance as to how this works?

**Comment by sofer** [comment]
@besarthoxhaj did it. It's hosted on heroku under the fac account and the repo is here: https://github.com/foundersandcoders/mail-fac

**Comment by iteles** [comment]
😇 thank you!

**Comment by sofer** [comment]
I think this is now working.

**Comment by iteles** [comment]
It is! :+1: :tada: Thank you :blush:
