### ISSUE TITLE
Proposed changes to website domain: foundersandcoders -> founderscoders

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#215]
I realise that messing with domains is not a brilliant idea from the SEO pov, but "*foundersandcoders*" feels to me like a bit of a mouthful. It's so long that we couldn't even use if for our twitter handle, which is already "*founderscoders*". I notice it most when giving people my email address over the phone.

We do have already have both the "*founderscoders.com*" and "*founderscoders.org*" domains, so changing them would be relatively trivial and we can easily redirect incoming email and web traffic.

I am not proposing to change the branding, just the domain. We are still "Founders & Coders". 

I would really value people's feedback on this.

**Comment by rub1e** [comment]
* What would you say if someone were naming a function and wanted to make its name less descriptive to save three characters?
* How often do you read out your email over the phone?
* What is the actual upshot from an SEO pov? If the impact on SEO is any more than minimal, I'd say the scant benefits of changing it aren't sufficient
* Come to think of it, what are the benefits? We're saving an "and"...

**Comment by oturnermajor** [comment]
I think foundersandcoders.com makes slightly more sense than founderscoders.com, since that is what our name is... No particularly strong feelings though.
