### ISSUE TITLE
Gender Data on Equalities Monitoring Guidance section of Application: Part 2

### ISSUE THREAD

**Issue by heatherlauren** [foundersandcoders/oursite#228]
The way gender data is being collected isn't very inclusive:

* 'How do you identify your gender?' is a better way to phrase the question
* Male / Female refers to biological sex; the options should be replaced with Man / Woman
* A 'Non-binary' option should be added for users who don't identify as a man or woman
* Users should be able to select more than one option - as the form stands now, a trans user has to choose between their gender identity and trans status in order to answer

**Comment by iteles** [comment]
❤️❤️ @heatheauren Could not agree more. I'm just in the middle of a full revision of the website language (that keeps getting interrupted by work) so the timing is perfect. 

Could you please submit a PR and assign to me? That would be amazing!

**Comment by iteles** [comment]
P.S. You would probably be interested in the conversation [here](https://github.com/foundersandcoders/oursite/pull/227) and in the corresponding issue (and we would very much appreciate your thoughts)

**Comment by heatherlauren** [comment]
Great news! I'm not sure how to access the form though, since it's run through Google Forms.

**Comment by iteles** [comment]
Ah, good point, it's a google form and not on the site. @sofer Can you give @heatherlauren access to the google form so she can make the changes?

**Comment by sofer** [comment]
@heatherlauren @iteles done. And thank you for the suggestion.
