### ISSUE TITLE
Review of prereqs

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#229]
I am not too sure about whether I still like Codecademy. Let's review our recommendations and maybe bring them into line with what we are doing on Monday evenings.

Also, there are some great regex resources out there, e.g. https://regexcrossword.com/ http://regexr.com/. These might be an improvement on https://www.codecademy.com/courses/javascript-intermediate-en-NJ7Lr

**Comment by sofer** [comment]
These could definitely be simplified. Given that we are now offering places two months in advance (a trend that seems likely to continue), we could push a lot of the other stuff into the period between an application being successful and the programme starting. 

For the [scholarships](http://www.foundersandcoders.com/scholarship/), I kept it super simple:

> If you are not familiar with the JavaScript programming language, then before you start on Codewars, we recommend an introductory course in JavaScript.

> We suggest you take a look at the Partner tutorials that teach JavaScript on code.org, such as Khan Academy or Codecademy. We also recommend the JavaScript Basics course on Udacity.

I suspect that this might be sufficient and less intimidating for some people.

**Comment by iteles** [comment]
I agree a review is needed, but I still think we need a measure of commitment before they are accepted onto the course - that is the true purpose of the pre-reqs

**Comment by sofer** [comment]
@iteles to be clear, I still think people should get up to 5 kyu and be active on gitter, it's just that I am less sure about insisting on four codecademy tracks and CSS Diner plus offering a dozen more "suggestions", some of which are questionable (e.g. the regex track on codecademy).
