### ISSUE TITLE
Font difficult to read

### ISSUE THREAD

**Issue by jackcarlisle** [foundersandcoders/oursite#233]
On the [Join Us](http://www.foundersandcoders.com/academy/) page the font is hard to make out against the background because of its text shadow

<img width="1504" alt="screen shot 2016-07-30 at 15 09 21" src="https://cloud.githubusercontent.com/assets/12450298/17271009/d3a788d8-5667-11e6-8338-e9ce25c1891f.png">

**Comment by sofer** [comment]
@jackcarlisle as an expedient, I have have given the font a heavier weight, which has reduced the problem.
