### ISSUE TITLE
Button text not centre aligned on Firefox 47.0

### ISSUE THREAD

**Issue by eliascodes** [foundersandcoders/oursite#234]
<img width="632" alt="screen shot 2016-07-31 at 15 38 17" src="https://cloud.githubusercontent.com/assets/12719553/17277204/06753b16-5735-11e6-93ac-2db735c9606d.png">
<img width="623" alt="screen shot 2016-07-31 at 15 38 33" src="https://cloud.githubusercontent.com/assets/12719553/17277206/12525554-5735-11e6-8b84-6dc487160949.png">

**Comment by des-des** [comment]
removing from milestone as unrelated
