### ISSUE TITLE
Path changes

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#242]
Minor irritation, and maybe not a big issue, but it has been bugging me for some time and if not now when?

/academy -> /programme

Also,

/agency -> /showcase

We are not an "academy" and we are not an agency. We may produce a tiny bit of linkrot (e.g. old twitter postings), but not sufficient to be too bothered. We can add a re-direct, if we really want to.

**Comment by iteles** [comment]
Redirects are pretty easy to do with any DNS provider, no reason why we shouldn't do that too 👍

**Comment by iteles** [comment]
@des-des The requirement here will change from the above, but we still need to make sure this is either covered or fixed as part of the changes made today please 😊 

Please reassign if changes are needed.

**Comment by des-des** [comment]
@sofer 

We currently have `portfolio` and `program`

Is that okay. Do you want me to change `portfolio` to `showcase`, or is that another page?
