### ISSUE TITLE
Site restructure

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#249]
Conversations with potential partnerships for the Nazareth programme have already started. There is therefore a relatively urgent need to for the website to support those conversations.

In advance of a site redesign, we are looking at restructuring the sections in an attempt to strengthen our message. Current thinking goes something like this:

+ Home page
  + Welcome message
  + Key themes
  + Testimonials
  + Meetups
+ Programme
 + Background
 + Mission
  + Schedule
+ Application
  + Preparation
  + Targets
  + Recommended material
+ Services
  + Model
  + Nonprofits
  + Accelerators
  + Employers
+ FAQs
+ Team
  + Management
  + Mentors
  + Developers
+ Press
  + English
  + Arabic
+ Partners

**Comment by iteles** [comment]
@sofer Is the suggestion that the solid bullet points are all top-level links accessed from the navbar or are some of them to be less prominent/footer links?

**Comment by sofer** [comment]
@iteles there are too many for the current nav. FAQ and Press can be dropped, perhaps, and Partners brought under Team.  @izaakrogan said he would take a look at it in the next couple of days. @rebeccaradding is drafting some copy.

**Comment by iteles** [comment]
Those were the two I was thinking could be footer links. 

It would also be good to A/B test having Apply in the main nav vs as a link from the homepage and programme pages (and any other relevant locations)

**Comment by iteles** [comment]
It would be good to fix these before @rebeccaradding writes all the copy so we can make sure we don't waste any of her hard work!

**Comment by rebeccaradding** [comment]
@iteles, copy is drafted. It's in a Google doc titled "FAC Website Content." Would love feedback if you have time to take a look!

**Comment by sofer** [comment]
I am thinking of contracting the "Services" section down to "Accelerators", so that the top-level might look something like this:

|HOME|ACCELERATORS|BOOTCAMPS|TEAM|
|----|----|----|----|

The middle two links would be:
http://www.foundersandcoders.com/founders
http://www.foundersandcoders.com/coders

Finally, our name makes sense!
