### ISSUE TITLE
A more detailed explanation of the application process

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#259]
See e.g. http://www.techcityuk.com/tech-nation-visa/

**Comment by rebeccaradding** [comment]
Here's a draft. Feedback? @iteles @nogainbar @harrygfox @sohilpandya 

Would like to get this up by end of week so we can start promoting the application on Facebook to Nazareth applicants who haven't started the prerequisites and are going to need as much time as possible.

https://docs.google.com/document/d/1zilbDrhR_c6-ildoOM5JDkucZyoADAEMreTZB3hHA40/edit?usp=sharing
