### ISSUE TITLE
Interim change to navigation

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#272]
Wider discussion to be had abour site redesign, but in the interim, the "founders" and "coders" top-level links are cute, but just plain confusing. 

I propose changing them to "portfolio" and "programme", so that the top-level nav will now read: 

||||||
|----|----|----|----|---|
|HOME|PORTFOLIO|PROGRAMME|COMMUNITY|OUR STORY|

**Comment by sofer** [comment]
And the "portfolio" section is in the process of being re-done.

**Comment by iteles** [comment]
@sofer As far as I can tell, the latest on this is now:
||||||
|----|----|----|----|---|
|HOME|PORTFOLIO|PROGRAMME|OUR STORY|OUR TEAM|APPLY

**Comment by sofer** [comment]
@iteles I hadn't thought of putting APPLY on the top level, but we could do and otherwise that looks right.

**Comment by des-des** [comment]
we are gonna put it in and see how it look? Easier to take it out than put it in..?

**Comment by sofer** [comment]
Done and ready to deploy.
