### ISSUE TITLE
Update programme page

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/oursite#276]
https://docs.google.com/document/d/1a1QCi_9FhIB0HaVlIqsccM3EFDOvfoCuBuoPgb8rOs8/edit#heading=h.q3vojnovrhj2

**Comment by bradreeder** [comment]
I've just:

- Changed the navbar link from "Coders" to "Programme"
- Deleted the old content and replaced it with the new content.
- Updated the assets folder to include some of the employer logos from the new content.
- Created a scss file for the Programme page.

**Comment by des-des** [comment]
Program page has new content in master.
