### ISSUE TITLE
Update the video link

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#280]
https://vimeo.com/188014263

**Comment by iteles** [comment]
@sofer Is this the video in the Programme page? #276

**Comment by nogainbar** [comment]
@iteles i think this is the link for the About page :)

**Comment by iteles** [comment]
@nogainbar I was going on the doc which doesn't include the video link there but in the programme page. I think the About page makes more sense personally!

**Comment by nogainbar** [comment]
@iteles, i think so too! so ive added it there for now as i think that is also what dan meant. if its not what we want we can change it tomorrow..

**Comment by rebeccaradding** [comment]
@nogainbar @iteles the video should be on only one page. I'm sorry if that was confusing.

If you think the About page makes more sense then that works for me! Let's take it down from Programme please.

**Comment by sofer** [comment]
In which case we need to remove the rogue video (pointing to a google drive!) under [programme](https://oursite-sofer.c9users.io/programme/).
