### ISSUE TITLE
Harp Compile

### ISSUE THREAD

**Issue by harrygfox** [foundersandcoders/oursite#3]
In my experience, Harps greedy consumption and conversion of markup partials into html can cause some serious headaches. Will the site be served from another server or is the idea to have it served from GH-pages again - requiring static html files at the root?

**Comment by izaakrogan** [comment]
Fair point. Let's start building. If we're having trouble down the line, we can change over to something else easily enough.

**Comment by harrygfox** [comment]
Re this - README.html

**Comment by sofer** [comment]
@harrygfox fair point, although that issue has now been resolved. I think as long as we have sensible workflows, harp is fine. Unlike with Jekyll, we have to compile before pushing to gh-pages, so the README + _harp source is on master, while the compiled version is on gh-pages.
