### ISSUE TITLE
Change FAQs to "Course Information"

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/oursite#309]
- [x] Rename FAQ page as "Course Information.

- [x] Take down all content on the FAQ page and replace with links to the two READMEs: 

- London course information: https://github.com/foundersandcoders/info/blob/master/london.md
- Nazareth course information: https://github.com/foundersandcoders/info/blob/master/nazareth.md

**Comment by ivanmauricio** [comment]
@rebeccaradding @sofer I will get started on this.

**Comment by ivanmauricio** [comment]
@rebeccaradding Just to clarify that we only want links on this page. Not the text that is on the READMEs?

**Comment by ivanmauricio** [comment]
Okay this is now done, I will close this issue.
