### ISSUE TITLE
Old image AND new image + extra links displaying on mobile homepage

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/oursite#325]
When I go to the homepage on mobile (tried on iPhone 6, Plus One X and Samsung Galaxy S6), I see the new image first, but if I keep scrolling I see an old image plus multiple old links directly underneath it. This second image needs to go :)

![img_2006](https://cloud.githubusercontent.com/assets/4185328/19811542/c318447c-9d29-11e6-9443-0df9bc8ef80f.PNG)
![img_2007](https://cloud.githubusercontent.com/assets/4185328/19811543/c44aa1be-9d29-11e6-8afb-43c2cff107e4.PNG)

**Comment by franzmoro** [comment]
@iteles the entire 2nd section needs to go, right?

**Comment by franzmoro** [comment]
btw I saw a desktop notification of a gitter message related to this, but couldn't find the chat room(?!there are so many!! 😧 )

**Comment by franzmoro** [comment]
In the large-screen version it seems as though it's intentional section to keep that section.
In the mobile version, this section is missing
<img width="736" alt="screen shot 2016-10-28 at 16 54 51" src="https://cloud.githubusercontent.com/assets/13413717/19812900/4f82e7f0-9d2f-11e6-885b-b09d363cb083.png">

**Comment by iteles** [comment]
@franzmoro You're right! It looks like it's *meant* to be there in the new site (if only we had some issues to capture the new design to confirm). The testimonials section is missing though and because the heads of most people in the top row are cut off in the second photo, it looks like a bug.

**Comment by franzmoro** [comment]
Ok, so I've resized the image a bit. This improves things especially on desktop. @iteles I suspect the testimonial section had been intentionally omitted as a shortcut, because the carousel css and js basically need complete re-writing to work on mobile.

**Comment by iteles** [comment]
In this case, I might be tempted to remove the group background image from the mobile website and having it just as the buttons because in my view, it looks like a bug (one image straight after the other is pretty odd).

**Comment by sofer** [comment]
I've merged and published the most recent pull request, but I agree that removing the group shot on mobile might make sense.

**Comment by franzmoro** [comment]
@sofer @iteles shall we have all three buttons on the top photo then?

**Comment by sofer** [comment]
We can lose the three buttons from the front page altogether on mobile--at least for now.

**Comment by franzmoro** [comment]
How about putting the three buttons in the 1st image like so (layout for mobile below)?
<img width="293" alt="screen shot 2016-10-31 at 18 54 06" src="https://cloud.githubusercontent.com/assets/13413717/19867361/8125d222-9f9b-11e6-862a-d1ffe040e5f4.png">

**Comment by des-des** [comment]
finished with #331
