### ISSUE TITLE
Adding Hasoub's logo to homepage

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/oursite#341]
We've recently formed a partnership with Hasoub, a community organization in Israel dedicated to nurturing entrepreneurship in Arab society. We've agreed to add their logo to the homepage. 

Logo: https://drive.google.com/open?id=0B-mliovLR9b_SE9jYzY1cEdVRmZBRThXZ09HeUF0ZDlYZ1dV

**Comment by cbauzac** [comment]
@rebeccaradding we are going to make a pull request to put this along with the other logos under the group picture but above the contact form. Is this right?
