### ISSUE TITLE
"Become a Developer" unreadable on mobile devices

### ISSUE THREAD

**Issue by sohilpandya** [foundersandcoders/oursite#362]
As you can see below, the header for "become a developer" is not very readable on mobile. Can we please make it black or more readable some other way?
<img width="339" alt="screen shot 2016-12-06 at 18 22 17" src="https://cloud.githubusercontent.com/assets/2305591/20937989/1cbaa95e-bbe1-11e6-9cd2-ce8fbef8cfd2.png">

Thanks X

**Comment by njsfield** [comment]
@denesnori is working on making the background image darker for readability

**Comment by iteles** [comment]
I quite like the light-ness of the image, I think the one on dwyl.io for example is just a bit dark and I quite like the happy/light-bright feel of the one on the F&C site.

Could we test making the weight of the font heavier first?

**Comment by njsfield** [comment]
I've made a few screenshots with comparisons. This shot shows greater font weight;
<img width="412" alt="screen shot 2016-12-12 at 18 32 18" src="https://cloud.githubusercontent.com/assets/16468314/21111575/11e4c9c0-c09a-11e6-885b-0f55569d6653.png">
Here is a shot with darker text;
<img width="410" alt="screen shot 2016-12-12 at 18 37 02" src="https://cloud.githubusercontent.com/assets/16468314/21111662/78590ffe-c09a-11e6-8eb2-da7109a311ad.png">
Here's the image with brightness reduced to 60%;
<img width="413" alt="screen shot 2016-12-12 at 18 33 14" src="https://cloud.githubusercontent.com/assets/16468314/21111700/afe95500-c09a-11e6-9dd7-5041e3ea6a34.png">
And here's the image brightness reduced and greater font weight;
<img width="413" alt="screen shot 2016-12-12 at 18 44 26" src="https://cloud.githubusercontent.com/assets/16468314/21111780/1299fa10-c09b-11e6-830a-4dc62ad122b5.png">
I like the combined approach of slight reduction and greater font weight, great for accessibility so should help with #348. Finally, check out this shot with this approach + relocated fac logo;
<img width="387" alt="screen shot 2016-12-12 at 18 49 30" src="https://cloud.githubusercontent.com/assets/16468314/21112061/268fac62-c09c-11e6-9c65-df547c20c2bb.png">
whatcha reckon? :)

**Comment by izaakrogan** [comment]
@njsfield what about killing the extra buttons and playing with the image position?
<img width="350" alt="screen shot 2016-12-12 at 19 37 58" src="https://cloud.githubusercontent.com/assets/4929798/21113757/abdc50d6-c0a2-11e6-8be3-d0c82f90770d.png">

**Comment by izaakrogan** [comment]
It's quite nice with the extra font weight too

<img width="347" alt="screen shot 2016-12-12 at 19 46 09" src="https://cloud.githubusercontent.com/assets/4929798/21114037/ad1d5642-c0a3-11e6-8595-9e1ef809fd2c.png">

**Comment by njsfield** [comment]
Add in radial-gradient, and you've got a deal
<img width="387" alt="screen shot 2016-12-12 at 20 35 12" src="https://cloud.githubusercontent.com/assets/16468314/21115718/85b3e858-c0aa-11e6-8957-7fce86d2c83b.png">

**Comment by iteles** [comment]
Yes @izaakrogan ! (but on the lighter colour photo @njsfield :blush:)

**Comment by njsfield** [comment]
The only downside with removing the testimonials + course info button would be that the user would not be able to navigate to those sections via the home page, as they are only visible on tablet+ (https://github.com/foundersandcoders/oursite/blob/master/_harp/index.ejs#L9)

**Comment by izaakrogan** [comment]
@njsfield nice effect with the lightbulb. How does it look with the brighter background image?

Good point on the buttons. Maybe we could to re-introduce the 'apply section' on the home page?

**Comment by njsfield** [comment]
It's subtle ; 
<img width="411" alt="screen shot 2016-12-13 at 10 04 15" src="https://cloud.githubusercontent.com/assets/16468314/21136115/38d9c0a8-c11c-11e6-9773-35612a11ab08.png">
How about that button removed; 
<img width="408" alt="screen shot 2016-12-13 at 10 08 11" src="https://cloud.githubusercontent.com/assets/16468314/21136122/40e64f0a-c11c-11e6-99aa-02a72cbea4d0.png">
And the apply section brought back?-
<img width="411" alt="screen shot 2016-12-13 at 10 08 18" src="https://cloud.githubusercontent.com/assets/16468314/21136135/4b77f4c8-c11c-11e6-9a34-7403049ff830.png">

**Comment by izaakrogan** [comment]
It looks great without the button but I think the call to action is important so probably your last suggestion - keep the apply button and remove it from the apply section.

As a side note, the apply button currently links to the programme page. It should probably link to the apply page.

**Comment by izaakrogan** [comment]
Should re-introduce the media-banner to split the landing and apply section?

**Comment by njsfield** [comment]
Like this?
<img width="416" alt="screen shot 2016-12-13 at 19 24 02" src="https://cloud.githubusercontent.com/assets/16468314/21155348/bdbc9820-c169-11e6-8fcd-54579702fc9a.png">

**Comment by izaakrogan** [comment]
Nice!

**Comment by njsfield** [comment]
I've made a pull request with these changes if you're happy to review?

**Comment by sohilpandya** [comment]
Thanks @njsfield 😍
