### ISSUE TITLE
part time programme nazareth

### ISSUE THREAD

**Issue by esraajb** [foundersandcoders/oursite#376]
im confused.

how long its going to last? why is it part time programme? why dont we just start Coding for everyone? (we make it on a daily basis(or 2-4 days a week) at least until the course starts).

**Comment by sofer** [comment]
We could call it a *"part-time preparatory programme"*, perhaps, to help applicants prepare for the full-time programme.

**Comment by rebeccaradding** [comment]
@esraajb great point. Part-time was the language suggested by our partners in Nazareth. I now think calling it Coding for Everyone makes more sense. The question now is how to communicate dates and times of these events both with the people who have signed up/will apply and with the wider community.

I have created an issue in the Nazareth repo and I suggest we continue the conversation there.

**Comment by des-des** [comment]
https://github.com/foundersandcoders/nazareth/issues/3
