### ISSUE TITLE
Training/School tab

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#38]
I suggest changing top-level from "School" to "Training" with structure as follows:

Training
- Developers
-- Build a website, React &c.
- Product managers
-- copy already provided
- School
-- about/apply - copy already provided

**Comment by iteles** [comment]
Is this going to be our only/main site?
My thinking here is that if the school is still at the centre of what we do, maybe it should consider letting it have it's own tab - either separate from general corporate-facing and client training or one that leads to the school-specific website if we're keeping it.

**Comment by jackpandas** [comment]
I suggest foregrounding the school within the training tab.
My reasoning is that demonstrating the capability to turn relative novices into junior developers in 2-4 months is a good platform for demonstrating the value of specialised short courses to other clients.

**Comment by sofer** [comment]
@iteles @jackpandas thanks for feedback. @iteles you are right. I have kept the school link. We may want to add training as a separate top-level link, but the copy is not yet ready. @izaakrogan and @besarthoxhaj  are looking at it this week, I hope also with input from @nelsonic @FilWisher @NataliaLKB @benjaminlees @MIJOTHY and anyone else who we can rope into doing a high-quality training session.
