### ISSUE TITLE
We need photographs of all of us

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/oursite#5]
@sofer to upload photo taken on FAC roof garden with new cohort.

**Comment by iteles** [comment]
https://plus.google.com/photos/105022275514300144972/albums/6149120837482523937?authkey=CMyvrP6poZW-uwE

**Comment by sofer** [comment]
@izaakrogan @iteles  I have made a pull request to add all the photos we have, but--mea culpa--none of fac4 :-(
