### ISSUE TITLE
FAC Motto?

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/oursite#7]

**Comment by izaakrogan** [comment]
Site currently reads, "We craft software to change the work". Can we make an improvement on this?

**Comment by sofer** [comment]
I actually quite like "a digital agency based in London". 

We could incorporate something about the school or about our company structure, but that might distract from the focus of the site, which is to get clients.

We could signal what sorts of clients we want or what sort of work we do, but I think we might still be a bit confused about this. In any case, the project trails can do this for us.

@iteles @nelsonic Can either of you improve on @izaakrogan's placeholder strapline?

**Comment by rub1e** [comment]
maybe because of my work background, but if i heard digital agency I'd think marketing/comms - how about something like __Creative applications and website solutions from an inspiring digital cooperative in London__ - though perhaps without the word "solutions". Or the direct route - __A cooperative of coders in London, building creative web applications and websites__? Or even more prosaic - __An agency of coders and web designers in London__?

**Comment by FilWisher** [comment]
I like @rub1e's branch "A cooperative of coders in London, building creative web applications and websites"

**Comment by iteles** [comment]
I agree on this. Prefer the simplicity of @rub1e's suggestion. 'Digital agency' doesn't really mean anything to people outside of this technology bubble (and I feel a bit dirty just saying the words).

**Comment by sofer** [comment]
@FilWisher @iteles @izaakrogan, I have gone with @rub1e's gently alliterative suggestion. Maybe we should move to Camberwell and, for completeness, we could swap the word 'constructing' for 'building'.

**Comment by nelsonic** [comment]
lol! Camberwell is pretty hot right now... :bulb:
http://www.camberwellarts.org.uk/ + http://thecamberwellopen.org/gallery/ :sunrise:
Its pretty much the new Bethnal Green ... South is the *New North* ... :stuck_out_tongue_winking_eye: 

But seriously, motto is a go. :+1:

**Comment by rub1e** [comment]
Worldwide web workers
Junior Javascript Jivers
Create, cooperate, code (that's not just alliteration, it's a tricolon crescendo as well)

I have more

**Comment by nelsonic** [comment]
@rub1e is on :fire: 
I'm *excited*! :star2:

**Comment by sofer** [comment]
@rub1e I had to look that up.

**Comment by nelsonic** [comment]
everyone loves a good [isocolon](http://en.wikipedia.org/wiki/Isocolon) :wink:
Even when its the same word ... 
> "*Education, Education, Education*" ...   :laughing:

**Comment by iteles** [comment]
:laughing: :+1:

**Comment by sofer** [comment]
We have shortened it (for now) to "A co-operative of coders in London", not because we prefer the sound of it, but because it lines up nicely.
