### ISSUE TITLE
main navbar drop-down

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/oursite#76]
when you hover over the navbar elements, it seems that the drop-down is based on hovering over the whole li element rather than the h3 within the li - feels a bit odd

**Comment by sofer** [comment]
@rub1e I prefer it like it is. If it was as you suggest the navbar would be appearing and disappearing as you rolled over the navbar, left to right. I don't think that would look nice. If we really wanted to be fancy, perhaps we could have the subnav links fade in and out when moving from one top-level item to another :-)
