### ISSUE TITLE
mobile site navbar

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/oursite#86]
really love the dropdown navbar on the mobile site, but there's an issue with the white box that contains the menu button: 

* on load, it takes up a quarter of the screen
* when you scroll down, it stays the same size, but it then halves in size when you get to just above the portfolio section
* and then if you have your keyboard open, the white box gets even smaller, so that it's thinner than the menu button which juts out below it.

**Comment by izaakrogan** [comment]
@rub1e can you check the behaviour on your phone now. Should be an improvement, if not perfect. Will come back to this over the weekend.

**Comment by izaakrogan** [comment]
@rub1e I think these specific issues are solved, although the mobile nav behaviour is still off. Seems to vary across device. If you get time, let me know how it looks at your end and a post separate issue for anything that still needs work.
