### ISSUE TITLE
training / schedule page

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/oursite#87]
the cursor in the link to request info about a training programme is a text cursor not a pointer cursor

**Comment by sofer** [comment]
@rub1e I think this may be fixed. Can you confirm?

**Comment by rub1e** [comment]
doesn't seem to be - it's the bit under "Request training for your organisation" just before "Our technology stack" - the text is "... get in touch". Sorry, should have been more precise in the first place!
 
Also just noticed it says intrested instead of interested in the same paragraph.

**Comment by sofer** [comment]
Got it.

**Comment by sofer** [comment]
@rub1e ready to close?
