### ISSUE TITLE
What do you think of the wireframes?

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/oursite#9]
https://docs.google.com/presentation/d/15Hee1UiwBPGG2RqKzNIFMAl93t6aeYdSBMSqVQo5WB8/edit?usp=sharing

**Comment by nelsonic** [comment]
Good outline so far.

**Comment by iteles** [comment]
@izaakrogan Looks good :blush: 
A couple of tiny questions:
+ Do you intend for the 'Team' section under 'Company' to have all the photos of every person who's ever been through F&C ever? 
+ Are you also adding some way to skip down to content further down or expecting people to scroll (for example, it might be a bit of scrolling on mobile to get from 'Course info' to 'Apply' in the 'School' section)?

**Comment by izaakrogan** [comment]
@iteles 
- Not everyone but I guess there will be a lot of images anyway. Maybe we should reverse the order of team and about/principles/history, so that we don't bury the latter.
- Yes, we should do something like that. A hover over drop-down could work well on Desktop. That still leaves touch devises to deal with.

**Comment by iteles** [comment]
Could be as simple as a secondary list of links appearing across the top of the page (under the main menu).

Oh, one more question: Are we keeping the [financial updates](https://github.com/foundersandcoders/money) to the school site or the 'company' site (this one)?

**Comment by sofer** [comment]
@izaakrogan 

Landing page: we might want some "partner" links at the bottom of the page.
Work page: duplication of "portfolio" section that appears on front page?
Blog: I am guessing we will want to separate out "stories" and the more technical blogs that we are going to start adding soon.

@iteles I think it would be good to have photos of all current members and students along with a selection of alumni under separate headings. btw we don't have any mugshots of fac4!

**Comment by izaakrogan** [comment]
@sofer 

I was thinking we might want a stripped down portfolio on our landing page and a full portfolio on the work page.
