### ISSUE TITLE
Missing links to portfolio pages

### ISSUE THREAD

**Issue by Lukars** [foundersandcoders/oursite#95]
Can you add a link to the websites that are featuread in "portfolio"

**Comment by sofer** [comment]
Agreed. We could do with a portfolio front here: http://www.foundersandcoders.com/portfolio/ and some way of navigating between portfolio projects.

**Comment by izaakrogan** [comment]
We will come back to this at the end of the month

**Comment by iteles** [comment]
I was doing clicking through yesterday and found this quite frustrating. Definitely worth adding :+1:

**Comment by izaakrogan** [comment]
I have hashed together something for this. If you have a more well thought-out solution, post it as a separate issue or make a pull request.
